
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package UI;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sebas
 */
public class AgregarTareas extends javax.swing.JFrame implements Runnable{
DefaultTableModel modelo;
String hora,minutos,segundos;
Thread hilo;
Calendar FechaActual = new GregorianCalendar();
Object[] o = new Object[3];
String[] c = new String[3];

    /**
     * Creates new form FrameTareas
     */
    public AgregarTareas() {
        initComponents();
        
        this.setResizable(false);
        
        lbFecha.setText(fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        modelo = (DefaultTableModel)Tabla.getModel();
        
        this.Tabla.setModel(modelo);
    }
    
    void agregar(){
        
    }
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE); 
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }

    public void run(){
        Thread current = Thread.currentThread();
        
        while (current == hilo){
            hora();
            lbHora.setText(hora+":"+minutos+":"+segundos);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHora = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTarea = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        txtday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbHora.setText("00:00:00");

        lbFecha.setText("DD/MM/YYYY");

        jLabel1.setText("Tarea:");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Completa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Propietario", "Tarea", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel2.setText("Dia:");

        jLabel3.setText("Propietario:");

        txtday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdayActionPerformed(evt);
            }
        });

        jLabel4.setText("Mes:");

        jLabel5.setText("Año:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Ventana Agregar Tareas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(88, 88, 88)
                        .addComponent(lbFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTarea))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtday, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txty, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(15, 15, 15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHora)
                    .addComponent(lbFecha)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
        //String date = dformat.format(datofecha.getDate());
        String propietario,tarea;
        int fecha,dia,mes,anno;
        propietario = txtPropietario.getText();
        dia = Integer.parseInt(txtday.getText());
        mes=Integer.parseInt(txtmes.getText());
        anno=Integer.parseInt(txty.getText());
        switch (mes){
            case 1:
                if (dia <= 31){
                    String mes1 ="Enero";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes1+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }      
            case 2:
                if (dia <= 28){
                    String mes2 ="Febrero";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes2+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 3:
                if (dia <= 31){
                    String mes3 ="Marzo";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes3+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido"); 
                }
            case 4:
                if (dia <= 30){
                    String mes4 ="Abril";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes4+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 5:
                if (dia <= 31){
                    String mes5 ="Mayo";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes5+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 6:
                if (dia <= 30){
                    String mes6 ="Junio";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes6+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 7:
                if (dia <= 31){
                    String mes7 ="Julio";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes7+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 8:
                if (dia <= 31){
                    String mes8 ="Agosto";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes8+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 9:
                if (dia <= 30){
                    String mes9 ="Septiembre";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes9+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 10:
                if (dia <= 31){
                    String mes8 ="Octubre";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes8+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 11:
                if (dia <= 30){
                    String mes11 ="Noviembre";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes11+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
            case 12:
                if (dia <= 31){
                    String mes12 ="Diciembre";
                    o[0] = txtPropietario.getText();
                    o[1] = txtTarea.getText();
                    o[2] = dia+"/"+mes12+"/"+anno;
                    JOptionPane.showMessageDialog(null,"Agregado exitosamente");
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Dia no permitido");
                }
        }
        //tarea = txtTarea.getText();
        //o[0] = txtPropietario.getText();
        //o[1] = txtTarea.getText();
        //o[2] = dia+"/"+mes+"/"+anno;
        modelo.addRow(o);
        //this.modelo.addRow(new Object[]{(date)});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        if (fila >= 0){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar fila");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int fila = Tabla.getRowCount();
        for (int i = fila-1; i >= 0; i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHora;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTarea;
    private javax.swing.JTextField txtday;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txty;
    // End of variables declaration//GEN-END:variables
}
