/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class MenuModificadorAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuModificadorAdmin
     */
    public MenuModificadorAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NuevoPrecioHabitacion = new javax.swing.JTextField();
        CantHabitacionesMod = new javax.swing.JTextField();
        btnModDatos = new javax.swing.JButton();
        btnVolverMod = new javax.swing.JButton();
        cmbModificador = new javax.swing.JComboBox<>();
        btnEscoger = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Modificador de datos en reservacion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Modificador de datos en reservacion");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Editar precio por habitacion");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Editar cantidad de habitaciones");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Asigne el nuevo precio");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Nueva cantidad de habitaciones");

        NuevoPrecioHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPrecioHabitacionActionPerformed(evt);
            }
        });

        btnModDatos.setText("Guardar");
        btnModDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModDatosActionPerformed(evt);
            }
        });

        btnVolverMod.setText("Volver");
        btnVolverMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverModActionPerformed(evt);
            }
        });

        cmbModificador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Double", "Triple", "Quad", "Queen", "King", "Doble-Doble", "Suite", "Suite presidencial" }));

        btnEscoger.setText("Escoger");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Escoger el tipo de habitacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(NuevoPrecioHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CantHabitacionesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolverMod)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModDatos)
                        .addGap(192, 192, 192))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbModificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEscoger)
                        .addGap(109, 109, 109)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscoger)
                    .addComponent(cmbModificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoPrecioHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantHabitacionesMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnModDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverMod)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoPrecioHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPrecioHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoPrecioHabitacionActionPerformed

    private void btnModDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModDatosActionPerformed
        int nuevoPrecio = 0, NuevaCantHab = 0;
        
        String mod = cmbModificador.getSelectedItem().toString();
        if (mod.equals("Individual")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Double")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Triple")){
           nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
           NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
           JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
           JOptionPane.showMessageDialog(null,"Informacion actualizada");
           cmbModificador.setSelectedIndex(0);
           NuevoPrecioHabitacion.setText(null);
           CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Quad")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Queen")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("King")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Doble-Doble")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Suite")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }
        
        if (mod.equals("Suite presidencial")){
            nuevoPrecio = Integer.parseInt(NuevoPrecioHabitacion.getText());
            NuevaCantHab = Integer.parseInt(CantHabitacionesMod.getText());
            JOptionPane.showMessageDialog(null,"Nuevo precio por habitacion: $"+ nuevoPrecio
                + "\nNueva cantidad de habitaciones: "+ NuevaCantHab);
            JOptionPane.showMessageDialog(null,"Informacion actualizada");
            cmbModificador.setSelectedIndex(0);
            NuevoPrecioHabitacion.setText(null);
            CantHabitacionesMod.setText(null);
        }        

    }//GEN-LAST:event_btnModDatosActionPerformed

    private void btnVolverModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverModActionPerformed
        PrincipalAdministrador X = new PrincipalAdministrador();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuModificadorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuModificadorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuModificadorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuModificadorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuModificadorAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantHabitacionesMod;
    private javax.swing.JTextField NuevoPrecioHabitacion;
    private javax.swing.JButton btnEscoger;
    private javax.swing.JButton btnModDatos;
    private javax.swing.JButton btnVolverMod;
    private javax.swing.JComboBox<String> cmbModificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
