/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */

/*Para añadir las cosas a la talbla estos son las variables:
    numeroRe=Es que almacena el numero de reserva
    numeroPla=Es que almacena el numero de placa
    tipo=Es que almacena el tipo de vehiculo
    modelo=Es que almacena el modelo del vehiculo
    parqueo=Parqueo Random
    plaza=La plaza Random donde se encuentra el vehiculo
    
*/




public class MenuParqueo extends javax.swing.JFrame {

    /**
     * Creates new form Ventanaparqueo
     */
    public MenuParqueo() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pfNumeroReserva = new javax.swing.JPasswordField();
        txtNumeroPlaca = new javax.swing.JTextField();
        cmbTipoVehiculo = new javax.swing.JComboBox<>();
        txtModeloVehiculo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 2, 24)); // NOI18N
        jLabel4.setText("Menu Parqueo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Dijite el numero de placa:");

        jLabel2.setText("Seleccione su tipo de vehículo:");

        jLabel3.setText("Dijite su número de reserva:");

        jLabel6.setText("Digite el modelo de  su vehiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 2, 24)); // NOI18N
        jLabel5.setText("Menu Parqueo");

        jLabel7.setText("Por favor llenar solamente si trae algun vehiculo");

        pfNumeroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfNumeroReservaActionPerformed(evt);
            }
        });

        cmbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motocicleta", "Automovil", "Pick-Up", "Microbus", "Autobus" }));
        cmbTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVehiculoActionPerformed(evt);
            }
        });

        txtModeloVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloVehiculoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pfNumeroReserva)
                            .addComponent(txtNumeroPlaca)
                            .addComponent(cmbTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModeloVehiculo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel5)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(pfNumeroReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtNumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
        
        RegistroParqueo a = new RegistroParqueo();
        
        
        int numeroRe,numeroPla;
        String modelo,tipo;
        ArrayList parqueos = new ArrayList();
        parqueos.add("Parqueo A");
        parqueos.add("Parqueo B");
        parqueos.add("Parqueo C");
        parqueos.add("Parqueo D");
        
        
        numeroRe =Integer.parseInt(pfNumeroReserva.getText().trim());
        numeroPla =Integer.parseInt(txtNumeroPlaca.getText().trim());
        modelo=txtModeloVehiculo.getText().trim();
        
        tipo =cmbTipoVehiculo.getSelectedItem().toString();
        if(tipo.equals("Motocicleta")){
            int parqueo = (int)(Math.random() * 4); 
            /*Random plazaR = new Random();
            int plaza = 1+plazaR.nextInt(15);*/
            int plaza = (int)(Math.random() * 15 + 1);
            JOptionPane.showMessageDialog(null,"El vehichulo "+tipo+" modelo " + modelo + " con la placa "+ numeroPla + " y el numero de reservacion " +numeroRe +"."
                                        + "\n Se encuentra en el " + parqueos.get(parqueo) + " en la plaza " + plaza);
            
            pfNumeroReserva.setText("");
            txtNumeroPlaca.setText("");
            cmbTipoVehiculo.setSelectedIndex(0);
            txtModeloVehiculo.setText("");
            
        }
        if(tipo.equals("Automovil")){
            int parqueo = (int)(Math.random() * 4); 
            /*Random plazaR = new Random();
            int plaza = 15+plazaR.nextInt(250);*/
            int plaza = (int)(Math.random() * 250 + 15);
            JOptionPane.showMessageDialog(null,"El vehichulo "+tipo+" modelo " + modelo + " con la placa "+ numeroPla + " y el numero de reservacion " +numeroRe +"."
                                        + "\n Se encuentra en el " + parqueos.get(parqueo) + " en la plaza " + plaza);
            
            pfNumeroReserva.setText("");
            txtNumeroPlaca.setText("");
            cmbTipoVehiculo.setSelectedIndex(0);
            txtModeloVehiculo.setText("");
        }
        if(tipo.equals("Pick-Up")){
            int parqueo = (int)(Math.random() * 4);
            /*Random plazaR = new Random();
            int plaza = 15+plazaR.nextInt(250);*/
            int plaza = (int)(Math.random() * 250 + 15);
            JOptionPane.showMessageDialog(null,"El vehichulo "+tipo+" modelo " + modelo + " con la placa "+ numeroPla + " y el numero de reservacion " +numeroRe +"."
                                        + "\n Se encuentra en el " + parqueos.get(parqueo) + " en la plaza " + plaza);
            
            pfNumeroReserva.setText("");
            txtNumeroPlaca.setText("");
            cmbTipoVehiculo.setSelectedIndex(0);
            txtModeloVehiculo.setText("");
        }
        if(tipo.equals("Microbus")){
            int parqueo = (int)(Math.random() * 4);
            /*Random plazaR = new Random();
            int plaza = 250+plazaR.nextInt(450);*/
            int plaza = (int)(Math.random() * 450 + 250);
            JOptionPane.showMessageDialog(null,"El vehichulo "+tipo+" modelo " + modelo + " con la placa "+ numeroPla + " y el numero de reservacion " +numeroRe +"."
                                        + "\n Se encuentra en el " + parqueos.get(parqueo) + " en la plaza " + plaza);
            
            pfNumeroReserva.setText("");
            txtNumeroPlaca.setText("");
            cmbTipoVehiculo.setSelectedIndex(0);
            txtModeloVehiculo.setText("");
        }
        if(tipo.equals("Autobus")){
            int parqueo = (int)(Math.random() * 4);
            /*Random plazaR = new Random();
            int plaza = 250+plazaR.nextInt(450);*/
            int plaza = (int)(Math.random() * 450 + 250);
            JOptionPane.showMessageDialog(null,"El vehichulo "+tipo+" modelo " + modelo + " con la placa "+ numeroPla + " y el numero de reservacion " +numeroRe +"."
                                        + "\n Se encuentra en el " + parqueos.get(parqueo) + " en la plaza " + plaza);
            
            pfNumeroReserva.setText("");
            txtNumeroPlaca.setText("");
            cmbTipoVehiculo.setSelectedIndex(0);
            txtModeloVehiculo.setText("");
            
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PrincipalHuesped V = new PrincipalHuesped();
        V.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void pfNumeroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfNumeroReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfNumeroReservaActionPerformed

    private void cmbTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoVehiculoActionPerformed

    private void txtModeloVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuParqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    public static javax.swing.JComboBox<String> cmbTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPasswordField pfNumeroReserva;
    public static javax.swing.JTextField txtModeloVehiculo;
    public static javax.swing.JTextField txtNumeroPlaca;
    // End of variables declaration//GEN-END:variables
}
