/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Datos.IniciarDatosCuenta;

/**
 *
 * @author PC
 */
public class PrincipalAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalAdministrador
     */
    public PrincipalAdministrador() {
        initComponents();
        for(int i=0;i<IniciarDatosCuenta.NuevasCuentas.size();i++){
            txtMostrarNombre.setText(String.valueOf(IniciarDatosCuenta.NuevasCuentas.get(i).getNombre()));
            txtMostrarApellidos.setText(String.valueOf(IniciarDatosCuenta.NuevasCuentas.get(i).getApellidos()));
            txtMostrarCedula.setText(String.valueOf(IniciarDatosCuenta.NuevasCuentas.get(i).getCedula()));
            txtMostrarEdad.setText(String.valueOf(IniciarDatosCuenta.NuevasCuentas.get(i).getEdad()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMostrarNombre = new javax.swing.JLabel();
        txtMostrarApellidos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMostrarCedula = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMostrarEdad = new javax.swing.JLabel();
        Barra = new javax.swing.JMenuBar();
        mMenuRegistros = new javax.swing.JMenu();
        mRReserva = new javax.swing.JMenuItem();
        mRVisitantes = new javax.swing.JMenuItem();
        mRParqueo = new javax.swing.JMenuItem();
        mModificador = new javax.swing.JMenu();
        mModificar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-usuario.png"))); // NOI18N

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        txtMostrarNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMostrarNombre.setText("jLabel3");

        txtMostrarApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMostrarApellidos.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
        jLabel4.setText("Cedula:");

        txtMostrarCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMostrarCedula.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
        jLabel5.setText("Edad:");

        txtMostrarEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMostrarEdad.setText("jLabel6");

        mMenuRegistros.setText("Menu de registros ");

        mRReserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mRReserva.setText("Menu Registro Reserva");
        mRReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRReservaActionPerformed(evt);
            }
        });
        mMenuRegistros.add(mRReserva);

        mRVisitantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mRVisitantes.setText("Menu Registro Visitantes");
        mRVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRVisitantesActionPerformed(evt);
            }
        });
        mMenuRegistros.add(mRVisitantes);

        mRParqueo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mRParqueo.setText("Menu Registro Parqueo");
        mRParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRParqueoActionPerformed(evt);
            }
        });
        mMenuRegistros.add(mRParqueo);

        Barra.add(mMenuRegistros);

        mModificador.setText("Modificador");

        mModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mModificar.setText("Modificar Info Habitacion");
        mModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificarActionPerformed(evt);
            }
        });
        mModificador.add(mModificar);

        Barra.add(mModificador);

        setJMenuBar(Barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMostrarApellidos)
                    .addComponent(txtMostrarNombre)
                    .addComponent(txtMostrarCedula)
                    .addComponent(txtMostrarEdad))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMostrarNombre))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMostrarApellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMostrarCedula)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMostrarEdad))
                .addGap(34, 34, 34)
                .addComponent(btnVolver1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mRReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRReservaActionPerformed
        RegistroReservas r = new RegistroReservas();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mRReservaActionPerformed

    private void mRVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRVisitantesActionPerformed
        RegistroVisitantes vi = new RegistroVisitantes();
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mRVisitantesActionPerformed

    private void mRParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRParqueoActionPerformed
        RegistroParqueo p = new RegistroParqueo();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mRParqueoActionPerformed

    private void mModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificarActionPerformed
        MenuModificadorAdmin r = new MenuModificadorAdmin();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mModificarActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        LogIn l = new LogIn();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu mMenuRegistros;
    private javax.swing.JMenu mModificador;
    private javax.swing.JMenuItem mModificar;
    private javax.swing.JMenuItem mRParqueo;
    private javax.swing.JMenuItem mRReserva;
    private javax.swing.JMenuItem mRVisitantes;
    private javax.swing.JLabel txtMostrarApellidos;
    private javax.swing.JLabel txtMostrarCedula;
    private javax.swing.JLabel txtMostrarEdad;
    private javax.swing.JLabel txtMostrarNombre;
    // End of variables declaration//GEN-END:variables
}
